config/routes.rb
Rails.application.routes.draw do

  get '/' => 'application#welcome'

  get '/about' => 'application#about'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#fbcreate'

  get '/indoor_plants/:id/buy' => 'indoor_plants#buy'

  get '/stores/:id/plants_sold' => 'stores#plants_sold', as: :plants_sold

  post '/indoor_plants/by_price' => 'indoor_plants#index'

  post '/stores/:id' => 'stores#show'

  resources :users, except: [:index] do
    resources :stores, only: [:index, :show, :new, :create]
  end
  
  resources :stores do
    resources :indoor_plants, except: [:index, :show]
  end

  resources :indoor_plants, except: [:show]

end

app/models/store.rb
class Store < ApplicationRecord
    validates :name, uniqueness: true
    
    belongs_to :user
    has_many :indoor_plants

    def plants_sold
        @x = []

        User.all.each do |user|
            user.indoor_plants.collect {|plant| @x << plant if plant.store_id == self.id}
        end

        @x
    end

    def most_sold_plant
        grouped_array = @x.group_by(&:itself)
        key, value = grouped_array.first
        best_selling_hash = grouped_array.map {|key, value| [key.name, value.length]}.to_h
        inverted_hash = best_selling_hash.sort_by {|key, value| -value}.to_h
        inverted_hash.keys[0]
    end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    include ApplicationHelper
    before_action :require_login

    def index
        @users = User.all
        
        # if !params[:user].blank?
        #     @stores = User.find_by(:id => params[:user]).stores
        if params[:user_id]
            @stores = User.find_by(:id => params[:user_id]).stores
        else
            @stores = Store.all
        end
    end

    def new
        @store = Store.new
    end

    def create
        @store = Store.new(store_params)
        @store.user_id = session[:user_id]

        if @store.valid?
            @store.save
            redirect_to store_path(@store)
        elsif 
            render :'/stores/new'
        end
    end

    def show
        @store = Store.find_by(:id => params[:id])

        if !params[:indoor_plant].blank?
            @indoor_plants = @store.indoor_plants.search(params[:indoor_plant])
        else
            @indoor_plants = @store.indoor_plants
        end
    end

    def edit
        @store = Store.find_by(:id => params[:id])
    end

    def update
        @store = Store.find_by(:id => params[:id])
        @store.update(store_params)

        if @store.valid?
            redirect_to store_path(@store)
        else
            render :'/stores/new'
        end
    end

    def destroy
        @store = Store.find_by(:id => params[:id])
        @store.indoor_plants.each {|plant| plant.destroy}
        @store.destroy
        redirect_to stores_path
    end

    def plants_sold
        @store = Store.find_by(:id => params[:id])
        render :plants_sold
    end

    private

    def store_params
        params.require(:store).permit(:name, :bio, :store_id)
    end

end

app/views/stores/_form.html.erb
<div class="error">
    <% if @store.errors.any? %>
        <% @store.errors.full_messages.each do |message| %>
            <%= message %>.<br>
        <% end %><br>
    <% end %>
</div>

<div class="form">
    <%= form_for(@store) do |f| %>
        <%= f.text_field :name, placeholder: "Please enter in a shop name.", required: true %><br><br>
        <%= f.text_field :bio, placeholder: "Please enter a bio for your shop.", required: true %><br><br>
        <%= f.submit "Submit" %>
    <% end %>
</div>

app/views/stores/edit.html.erb
<%= render 'form' %>

<div class="special">
    <%= link_to "Delete Store", @store, method: :delete, data: { confirm: "Are you sure you want to delete this Store?" } %>
</div>

app/views/stores/index.html.erb
<div class="content">
  <% if params[:user_id] %>
    <% if @stores.empty? %>
      <p>You do not own any shops.</p>
    <% else %>
      <table>
        <tr>
          <th>Store</th>
          <th>Plants</th>
          <th>Income</th>
          <th>Plants Sold</th>
          <th>Most Sold Plant</th>
        </tr>

        <% @stores.each.with_index(1) do |store, index| %>
          <tr>
          <td><%= link_to store.name, user_store_path(store.user, store) %></td>
          <td><%= store.indoor_plants.count %></td>
          <td><%= store.income.nil? ? 0:store.income %></td>
          <td><%= link_to store.plants_sold.count, plants_sold_path(store) %></td>
          <td><%= store.most_sold_plant %></td>
          </tr>
        <% end %>
      </table>
    <% end %>

  <div class="special">
  <%= link_to 'Create New Store', new_user_store_path %>
  </div>

  <% else %>
    <table>
      <tr>
          <th>Store</th>
          <th>Plants</th>
          <th>Owner</th>
      </tr>

      <% @stores.each do |store| %>
        <tr>
          <td><%= link_to store.name, store_path(store) %></td>
          <td><%= store.indoor_plants.count %></td>
          <td><%= store.user.name %></td>
        </tr>
      <% end %>
    </table><br><br>    

    <div class="filter">
      <%= form_tag("/stores", method: "get") do %>
        <%= select_tag "user", options_from_collection_for_select(@users, "id", "name"), include_blank: true %>
        <%= submit_tag("Filter", :style => "width:100px; height: 20px;") %>
      <% end %>
    </div>

  <% end %>
</div>

app/views/stores/new.html.erb
<%= render 'form' %>

app/views/stores/plants_sold.erb
<div class="content">
    <% if @store.plants_sold.empty? %>
        <p>You have not sold any plants yet.</p>
    <% else %>
        <% @store.plants_sold.each do |plant| %>
            <p><%= plant.name %></p>
        <% end %>
    <% end %>
</div>

app/views/stores/show.html.erb
<div class="error">
    <p><%= flash[:message] %></p>
</div>

<div class="filter">
<%= form_tag("/stores/#{@store.id}", method: "POST") do %>
  <%= text_field_tag :indoor_plant, nil, :class => 'plant_filter' %>
  <%= submit_tag("Filter by Plant", :style => "width:100px; height: 20px;") %>
<% end %>
</div>

<div class="content">
    <h2><%= @store.name %></h2>

    <div class="bio">
        <p><%= @store.bio %><p>
    </div>

    <h2>Plants in Stock</h2>
    
    <% @indoor_plants.each do |plant| %>

        <div class="store_plants">
            <img src="<%= plant.image %>"><br>
            $<%= plant.price %><br>
            <%= plant.name %><br>

            <% if session[:user_id] == @store.user_id %>
                <%= link_to 'Edit this Plant', edit_indoor_plant_path(plant) %><br>
            <% else %>
                <%= link_to 'Buy this Plant', "/indoor_plants/#{plant.id}/buy" %><br>
            <% end %>
        </div>

    <% end %>
</div>


<div class="special">
    <% if session[:user_id] == @store.user_id %>
        <%= link_to "Edit #{@store.name}", edit_store_path(@store) %> 
        <%= link_to 'Add Plants to Store', new_store_indoor_plant_path(@store) %> 
    <% end %>
</div>