config/routes.rb
Rails.application.routes.draw do

  get '/' => 'application#welcome'

  get '/about' => 'application#about'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#fbcreate'

  get '/indoor_plants/:id/buy' => 'indoor_plants#buy'

  get '/stores/:id/plants_sold' => 'stores#plants_sold', as: :plants_sold

  post '/indoor_plants/by_price' => 'indoor_plants#index'

  post '/stores/:id' => 'stores#show'

  resources :users, except: [:index] do
    resources :stores, only: [:index, :show, :new, :create]
  end
  
  resources :stores do
    resources :indoor_plants, except: [:index, :show]
  end

  resources :indoor_plants, except: [:show]

end

app/models/user.rb
class User < ApplicationRecord
    validates :email, uniqueness: true
    validates :cash, numericality: { greater_than_or_equal_to: 0 }
    has_secure_password

    has_many :stores
    has_many :user_indoor_plants
    has_many :indoor_plants, through: :user_indoor_plants
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        
        if @user.valid?
            @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        elsif 
            render :'/users/new'
        end
    end

    def show
        @user = User.find_by(:id => params[:id])
    end

    def edit
        @user = User.find_by(:id => params[:id])
    end

    def update
        @user = User.find_by(:id => params[:id])
        @user.update(user_params)
        
        if @user.valid?
            redirect_to @user
        else
            render :'/users/edit'
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :name, :cash)
    end
    
end

app/views/users/edit.html.erb
<div class="error">
    <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |message| %>
            <%= message %>.<br>
        <% end %><br>
    <% end %>
</div>

<div class="form">
    <%= form_for(@user) do |f| %>
        <%= f.text_field :name, placeholder: "What would you like to be called?" %><br><br>
        <%= f.number_field :cash, placeholder: "How much cash do you have?" %><br><br>        
        <%= f.submit "Submit" %>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="error">
    <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |message| %>
            <%= message %>.<br>
        <% end %><br>
    <% end %>
</div>


<div class="form">
    <%= form_for(@user, url:'/signup') do |f| %>
        <%= f.email_field :email, placeholder: "Please enter an email.", required: true %><br><br>
        <%= f.password_field :password, placeholder: "Please enter in a password.", required: true %><br><br>
        <%= f.text_field :name, placeholder: "What would you like to be called?", required: true %><br><br>
        <%= f.number_field :cash, placeholder: "How much cash do you have?" %><br><br>
        <%= f.submit "Submit" %>
    <% end %>
</div>

<div class="special">
<%= link_to('Facebook SignUp', '/auth/facebook') %>
</div>

app/views/users/show.html.erb
<div class="content">
    <h2>You own <%= pluralize(@user.indoor_plants.count, 'plant') %>.</h2>
    <% @user.indoor_plants.each do |plant| %>
        <p><%= plant.name %></p>
    <% end %>
</div>

<div class="special">
    <%= link_to 'My Shops', user_stores_path(@user) %>
    <%= link_to "Your balance is $#{@user.cash}", edit_user_path %>
</div>